services:
  web:
    build: .
    ports:
      - "${CJ_DOCKER_PORT:-8080}:8080"
    volumes:
      - .:/app # Mounts your local project directory to the container's working directory for live development
